// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShipbuData;

#nullable disable

namespace MigrationsMySQL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240114174720_Address")]
    partial class Address
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ShipbuData.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("ShipbuData.TransportAcademyVideo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("DescriptionEn")
                        .HasColumnType("longtext");

                    b.Property<string>("DescriptionTr")
                        .HasColumnType("longtext");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2048)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NameTr")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("NameTr")
                        .IsUnique();

                    b.ToTable("TransportAcademyVideos");
                });

            modelBuilder.Entity("ShipbuData.TransportDistrict", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsAmazonDepot")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NameTr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("TransportDistricts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("05bb9082-20a8-4114-946b-cce72cedab19"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Eastern USA",
                            NameTr = "Doğu Amerika",
                            RegionId = new Guid("c194434c-7a4d-4d70-98df-1ecc78a333aa")
                        },
                        new
                        {
                            Id = new Guid("0c02aa0a-b0d4-477a-b4e9-0a5073d323bf"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Central USA",
                            NameTr = "Merkez Amerika",
                            RegionId = new Guid("c194434c-7a4d-4d70-98df-1ecc78a333aa")
                        },
                        new
                        {
                            Id = new Guid("34e425db-ff6c-4ab7-ac14-a1bd7a7c94a8"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Western USA",
                            NameTr = "Batı Amerika",
                            RegionId = new Guid("c194434c-7a4d-4d70-98df-1ecc78a333aa")
                        },
                        new
                        {
                            Id = new Guid("2b26b58b-050c-46a7-8567-2325c31fa6fb"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "ONT8",
                            NameTr = "ONT8",
                            RegionId = new Guid("c194434c-7a4d-4d70-98df-1ecc78a333aa")
                        },
                        new
                        {
                            Id = new Guid("3bf2da8a-0a2c-4a8f-99c9-35742cb7fa2e"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "LGB8",
                            NameTr = "LGB8",
                            RegionId = new Guid("c194434c-7a4d-4d70-98df-1ecc78a333aa")
                        },
                        new
                        {
                            Id = new Guid("dbe61b00-89ef-493c-8930-9d41a402a987"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "LAX9",
                            NameTr = "LAX9",
                            RegionId = new Guid("c194434c-7a4d-4d70-98df-1ecc78a333aa")
                        },
                        new
                        {
                            Id = new Guid("ccd6ecfe-c907-4777-96ad-40ab41b7ac06"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "SBD1",
                            NameTr = "SBD1",
                            RegionId = new Guid("c194434c-7a4d-4d70-98df-1ecc78a333aa")
                        },
                        new
                        {
                            Id = new Guid("6d332a8f-0bcd-4b81-9c59-6965f4ab40ae"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "SCK4",
                            NameTr = "SCK4",
                            RegionId = new Guid("c194434c-7a4d-4d70-98df-1ecc78a333aa")
                        },
                        new
                        {
                            Id = new Guid("76adc0f7-ac5d-43cd-9983-eae135865030"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "SMF3",
                            NameTr = "SMF3",
                            RegionId = new Guid("c194434c-7a4d-4d70-98df-1ecc78a333aa")
                        },
                        new
                        {
                            Id = new Guid("80ff3e90-dcb9-4bc3-9590-e3a2c331a0ec"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "VGT3",
                            NameTr = "VGT2",
                            RegionId = new Guid("c194434c-7a4d-4d70-98df-1ecc78a333aa")
                        },
                        new
                        {
                            Id = new Guid("72516348-d8e7-4ce3-af4e-f97b77897f89"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "GYR2",
                            NameTr = "GYR2",
                            RegionId = new Guid("c194434c-7a4d-4d70-98df-1ecc78a333aa")
                        },
                        new
                        {
                            Id = new Guid("5f0411d9-fc63-4dd4-a03f-50c26f0829c6"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "GYR3",
                            NameTr = "GYR3",
                            RegionId = new Guid("c194434c-7a4d-4d70-98df-1ecc78a333aa")
                        },
                        new
                        {
                            Id = new Guid("76e0d1b5-4fb7-4dc7-bcb1-1fadff9acc92"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "LAS1",
                            NameTr = "LAS1",
                            RegionId = new Guid("c194434c-7a4d-4d70-98df-1ecc78a333aa")
                        },
                        new
                        {
                            Id = new Guid("123a8e96-b5f2-4459-a896-da06599036cf"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "SJC7",
                            NameTr = "SJC7",
                            RegionId = new Guid("c194434c-7a4d-4d70-98df-1ecc78a333aa")
                        },
                        new
                        {
                            Id = new Guid("98ead996-828c-4a6f-99c2-914b7c8110ef"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "KRB1",
                            NameTr = "KRB1",
                            RegionId = new Guid("c194434c-7a4d-4d70-98df-1ecc78a333aa")
                        },
                        new
                        {
                            Id = new Guid("5abcb711-259a-48dc-9817-2e5b988d690a"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "KRB4",
                            NameTr = "KRB4",
                            RegionId = new Guid("c194434c-7a4d-4d70-98df-1ecc78a333aa")
                        },
                        new
                        {
                            Id = new Guid("b90943d8-f764-42d3-8fca-da1ba2378634"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "SBD2",
                            NameTr = "SBD2",
                            RegionId = new Guid("c194434c-7a4d-4d70-98df-1ecc78a333aa")
                        },
                        new
                        {
                            Id = new Guid("6d63584c-813f-48de-9b19-df143f83d2f7"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "SBD3",
                            NameTr = "SBD3",
                            RegionId = new Guid("c194434c-7a4d-4d70-98df-1ecc78a333aa")
                        },
                        new
                        {
                            Id = new Guid("d484cf5d-d07d-4e01-8aa4-c87747fa68fe"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "FTW1",
                            NameTr = "FTW1",
                            RegionId = new Guid("c194434c-7a4d-4d70-98df-1ecc78a333aa")
                        },
                        new
                        {
                            Id = new Guid("573da713-55b6-4505-9bb0-1e033f7c47e5"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "Vancouver YVR",
                            NameTr = "Vancouver YVR",
                            RegionId = new Guid("aaaa0d64-abd7-4e96-aa49-35d4253e014f")
                        },
                        new
                        {
                            Id = new Guid("637a3cf8-e91a-4e46-8ccf-d1bfcbaa19e3"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "Calgary YYC",
                            NameTr = "Calgary YYC",
                            RegionId = new Guid("aaaa0d64-abd7-4e96-aa49-35d4253e014f")
                        },
                        new
                        {
                            Id = new Guid("82060812-b989-4340-bd2e-8840585a8acf"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "Calgary YEG",
                            NameTr = "Calgary YEG",
                            RegionId = new Guid("aaaa0d64-abd7-4e96-aa49-35d4253e014f")
                        },
                        new
                        {
                            Id = new Guid("545149ad-862b-4e00-a5d6-e3492d68463b"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "Toronto YYZ",
                            NameTr = "Toronto YYZ",
                            RegionId = new Guid("aaaa0d64-abd7-4e96-aa49-35d4253e014f")
                        },
                        new
                        {
                            Id = new Guid("829f6814-b1a3-43f0-8d71-f2ea928e743b"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "Ottawa YOW",
                            NameTr = "Ottawa YOW",
                            RegionId = new Guid("aaaa0d64-abd7-4e96-aa49-35d4253e014f")
                        },
                        new
                        {
                            Id = new Guid("ff9e1ee3-91cc-404f-ae3f-4a4c8ad891f7"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "Ottawa YUL",
                            NameTr = "Ottawa YUL",
                            RegionId = new Guid("aaaa0d64-abd7-4e96-aa49-35d4253e014f")
                        },
                        new
                        {
                            Id = new Guid("431d73fb-827d-43c2-8ee3-98568d1cfcf8"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Bussiness Private Address",
                            NameTr = "Kurumsal/Bireysel Adres",
                            RegionId = new Guid("aaaa0d64-abd7-4e96-aa49-35d4253e014f")
                        },
                        new
                        {
                            Id = new Guid("9495dd9f-53c2-41c5-8680-34539a483a42"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "Edmonton YEG1",
                            NameTr = "Edmonton YEG1",
                            RegionId = new Guid("aaaa0d64-abd7-4e96-aa49-35d4253e014f")
                        },
                        new
                        {
                            Id = new Guid("de1cfc73-52a1-4c72-aed7-1c67a588e436"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "Toronto YOO",
                            NameTr = "Toronto YOO",
                            RegionId = new Guid("aaaa0d64-abd7-4e96-aa49-35d4253e014f")
                        },
                        new
                        {
                            Id = new Guid("bb88a4e3-a99f-45e4-a753-cb430b608a4f"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "Toronto YHM",
                            NameTr = "Toronto YHM",
                            RegionId = new Guid("aaaa0d64-abd7-4e96-aa49-35d4253e014f")
                        },
                        new
                        {
                            Id = new Guid("a42ea92c-d563-4eb8-bd25-83a3ac1217dc"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "Vancouver YXX",
                            NameTr = "Vancouver YXX",
                            RegionId = new Guid("aaaa0d64-abd7-4e96-aa49-35d4253e014f")
                        },
                        new
                        {
                            Id = new Guid("e7a610f5-1fe9-41e2-8493-34424d982b9b"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "UK",
                            NameTr = "İngiltere",
                            RegionId = new Guid("5d751653-be94-44f4-afbe-5baf410ae321")
                        },
                        new
                        {
                            Id = new Guid("cb7fa78d-6de7-4838-9e54-c279bea798b0"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Germany",
                            NameTr = "Almanya",
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883")
                        },
                        new
                        {
                            Id = new Guid("78587899-2653-4be7-b07e-13a7596d5649"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "France",
                            NameTr = "Fransa",
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883")
                        },
                        new
                        {
                            Id = new Guid("e1371a95-daa6-4c22-8bcd-c86e5ee03203"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Poland",
                            NameTr = "Polonya",
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883")
                        },
                        new
                        {
                            Id = new Guid("cb39b0c9-34bb-4f55-a39b-a575aff157b2"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Czech Rep.",
                            NameTr = "Çekya",
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883")
                        },
                        new
                        {
                            Id = new Guid("660348c5-b814-42bf-a1b9-df56696f3c75"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Belgium",
                            NameTr = "Belçika",
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883")
                        },
                        new
                        {
                            Id = new Guid("38df3f9b-f88b-4c6d-9a36-76fe0d3e1792"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Austria",
                            NameTr = "Avusturya",
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883")
                        },
                        new
                        {
                            Id = new Guid("8603813c-d724-4d63-8013-c273c9fe5fbc"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Luxembourg",
                            NameTr = "Lüksemburg",
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883")
                        },
                        new
                        {
                            Id = new Guid("7ddb170b-5696-4abe-a5a8-b6424a966ba9"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Spain",
                            NameTr = "İspanya",
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883")
                        },
                        new
                        {
                            Id = new Guid("8b08542b-6c77-4d8e-8d54-329ceec6c1e1"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Italy",
                            NameTr = "İtalya",
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883")
                        },
                        new
                        {
                            Id = new Guid("52e63491-43b4-47cc-b53e-8384aac7c07c"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Netherlands",
                            NameTr = "Hollanda",
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883")
                        },
                        new
                        {
                            Id = new Guid("58a45e41-a7fe-4dec-9a8e-3bbf38455e5f"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Greece",
                            NameTr = "Yunanistan",
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883")
                        },
                        new
                        {
                            Id = new Guid("ee896fe1-1434-4136-a70e-d2c9fa49d902"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Denmark",
                            NameTr = "Danimarka",
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883")
                        },
                        new
                        {
                            Id = new Guid("3c4fedcc-eaeb-4480-8574-c759e9aa2f9d"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Sweden",
                            NameTr = "İsveç",
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883")
                        },
                        new
                        {
                            Id = new Guid("da5d4f5e-79ac-4b69-b0f5-cf027053ec8c"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Finland",
                            NameTr = "Fillandiya",
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883")
                        },
                        new
                        {
                            Id = new Guid("bc3767bc-68d7-400d-ae61-707fc3bb5878"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Slovakia",
                            NameTr = "Slovakya",
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883")
                        },
                        new
                        {
                            Id = new Guid("291c8b1e-1eb6-4bc0-b714-86e79ed31316"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Slovenia",
                            NameTr = "Slovenya",
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883")
                        },
                        new
                        {
                            Id = new Guid("6de69db5-e0a5-4fe3-95a9-df3721f50d0b"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Hungary",
                            NameTr = "Macaristan",
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883")
                        },
                        new
                        {
                            Id = new Guid("e7b21a66-1c15-49cf-9ff9-c8b3455ba57d"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Portugal",
                            NameTr = "Portekiz",
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883")
                        },
                        new
                        {
                            Id = new Guid("e7777c20-3abb-4a39-af05-11fcee8f7534"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Croatia",
                            NameTr = "Hırvatistan",
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883")
                        },
                        new
                        {
                            Id = new Guid("b93226d5-2642-4705-99ca-734af02c624b"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Estonia",
                            NameTr = "Estonya",
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883")
                        },
                        new
                        {
                            Id = new Guid("da7b0a60-d6ca-44d4-9e28-d5d804cd7a64"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Latvia",
                            NameTr = "Latviya",
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883")
                        },
                        new
                        {
                            Id = new Guid("869993cb-ccd8-498f-880c-97f0e02f2846"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Bulgaria",
                            NameTr = "Bulgaristan",
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883")
                        },
                        new
                        {
                            Id = new Guid("18351822-a469-408c-b8a9-f17dbff1020a"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Monaco",
                            NameTr = "Monako",
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883")
                        },
                        new
                        {
                            Id = new Guid("803e5fb5-2a8f-4e42-a544-071b0b9fcecf"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Ireland",
                            NameTr = "Irlanda",
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883")
                        },
                        new
                        {
                            Id = new Guid("3a52e207-c517-49a2-98d4-2998f29f1ecd"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Romania",
                            NameTr = "Romanya",
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883")
                        });
                });

            modelBuilder.Entity("ShipbuData.TransportFee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DistrictId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MethodId")
                        .HasColumnType("char(36)");

                    b.Property<int>("MinWeight")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("MethodId");

                    b.ToTable("TransportFees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("53cfa498-8f41-45a4-a17c-8e466caa44ce"),
                            DistrictId = new Guid("05bb9082-20a8-4114-946b-cce72cedab19"),
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            MinWeight = 0,
                            Value = 10m
                        },
                        new
                        {
                            Id = new Guid("ae730878-6f27-43fe-8540-e4be8e4e8dc0"),
                            DistrictId = new Guid("05bb9082-20a8-4114-946b-cce72cedab19"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 23,
                            Value = 2.37m
                        },
                        new
                        {
                            Id = new Guid("891419b8-8ec0-465f-bf2a-504d9a98d2e7"),
                            DistrictId = new Guid("05bb9082-20a8-4114-946b-cce72cedab19"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 71,
                            Value = 2.22m
                        },
                        new
                        {
                            Id = new Guid("fddfc036-159e-4f93-9dae-96288b1d5bdd"),
                            DistrictId = new Guid("05bb9082-20a8-4114-946b-cce72cedab19"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 101,
                            Value = 1.57m
                        },
                        new
                        {
                            Id = new Guid("bf240aa3-b278-476b-9c6b-db1155af6593"),
                            DistrictId = new Guid("05bb9082-20a8-4114-946b-cce72cedab19"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 301,
                            Value = 1.50m
                        },
                        new
                        {
                            Id = new Guid("0e09c636-be6c-46da-be4f-f0f677b4147d"),
                            DistrictId = new Guid("05bb9082-20a8-4114-946b-cce72cedab19"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 1501,
                            Value = 1.47m
                        },
                        new
                        {
                            Id = new Guid("a75ae6e2-82ce-4c39-a6e4-b2a5ff2d0bab"),
                            DistrictId = new Guid("0c02aa0a-b0d4-477a-b4e9-0a5073d323bf"),
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            MinWeight = 0,
                            Value = 10m
                        },
                        new
                        {
                            Id = new Guid("5d700003-4975-449d-8d33-f2a5eddbeebf"),
                            DistrictId = new Guid("0c02aa0a-b0d4-477a-b4e9-0a5073d323bf"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 23,
                            Value = 2.22m
                        },
                        new
                        {
                            Id = new Guid("70e4af96-17e7-4341-bcb4-1ba6bdff8f9c"),
                            DistrictId = new Guid("0c02aa0a-b0d4-477a-b4e9-0a5073d323bf"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 71,
                            Value = 2.08m
                        },
                        new
                        {
                            Id = new Guid("d776447b-ce98-45af-a031-50ddf90d5e2c"),
                            DistrictId = new Guid("0c02aa0a-b0d4-477a-b4e9-0a5073d323bf"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 101,
                            Value = 1.43m
                        },
                        new
                        {
                            Id = new Guid("3490aebe-b720-4577-ab5d-7074eac48237"),
                            DistrictId = new Guid("0c02aa0a-b0d4-477a-b4e9-0a5073d323bf"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 301,
                            Value = 1.36m
                        },
                        new
                        {
                            Id = new Guid("20769105-fdd5-4818-9b90-a8f30f02d8b5"),
                            DistrictId = new Guid("0c02aa0a-b0d4-477a-b4e9-0a5073d323bf"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 1501,
                            Value = 1.33m
                        },
                        new
                        {
                            Id = new Guid("fa6159af-d91c-4fe2-909c-d0625db57589"),
                            DistrictId = new Guid("34e425db-ff6c-4ab7-ac14-a1bd7a7c94a8"),
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            MinWeight = 0,
                            Value = 10m
                        },
                        new
                        {
                            Id = new Guid("e4c62f9c-ccbb-42bd-9860-684c4d231ab9"),
                            DistrictId = new Guid("34e425db-ff6c-4ab7-ac14-a1bd7a7c94a8"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 23,
                            Value = 2.08m
                        },
                        new
                        {
                            Id = new Guid("86c0461f-d53a-4801-98b7-b7515dd40a3b"),
                            DistrictId = new Guid("34e425db-ff6c-4ab7-ac14-a1bd7a7c94a8"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 71,
                            Value = 1.93m
                        },
                        new
                        {
                            Id = new Guid("1e73c45f-b935-44ba-83aa-df6b31be7fa6"),
                            DistrictId = new Guid("34e425db-ff6c-4ab7-ac14-a1bd7a7c94a8"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 101,
                            Value = 1.57m
                        },
                        new
                        {
                            Id = new Guid("c4731c16-77cb-4dc5-bab9-045dd13e8f3a"),
                            DistrictId = new Guid("34e425db-ff6c-4ab7-ac14-a1bd7a7c94a8"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 301,
                            Value = 1.82m
                        },
                        new
                        {
                            Id = new Guid("0b4a5faf-e99c-423e-8fb0-3e3da466b02e"),
                            DistrictId = new Guid("34e425db-ff6c-4ab7-ac14-a1bd7a7c94a8"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 1501,
                            Value = 1.82m
                        },
                        new
                        {
                            Id = new Guid("1cae0400-32f1-4959-8c1a-26ae81add659"),
                            DistrictId = new Guid("2b26b58b-050c-46a7-8567-2325c31fa6fb"),
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            MinWeight = 0,
                            Value = 10m
                        },
                        new
                        {
                            Id = new Guid("84ee90bc-fee0-485f-adb1-7fa39ee9e3b3"),
                            DistrictId = new Guid("2b26b58b-050c-46a7-8567-2325c31fa6fb"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 101,
                            Value = 0.87m
                        },
                        new
                        {
                            Id = new Guid("71bd9a4d-e0c3-4bc6-be51-1f6b77ec81a5"),
                            DistrictId = new Guid("2b26b58b-050c-46a7-8567-2325c31fa6fb"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 101,
                            Value = 1.43m
                        },
                        new
                        {
                            Id = new Guid("23cedabe-c27b-491e-be1e-1db5b03b1a3c"),
                            DistrictId = new Guid("3bf2da8a-0a2c-4a8f-99c9-35742cb7fa2e"),
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            MinWeight = 0,
                            Value = 10m
                        },
                        new
                        {
                            Id = new Guid("c40b5074-8566-4467-b9cd-5b6a3447b3c6"),
                            DistrictId = new Guid("3bf2da8a-0a2c-4a8f-99c9-35742cb7fa2e"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 101,
                            Value = 0.87m
                        },
                        new
                        {
                            Id = new Guid("988046c7-e381-4c8c-96e1-f1420a6779ae"),
                            DistrictId = new Guid("3bf2da8a-0a2c-4a8f-99c9-35742cb7fa2e"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 101,
                            Value = 1.46m
                        },
                        new
                        {
                            Id = new Guid("960a37d1-44de-47a0-b10a-0c1293835729"),
                            DistrictId = new Guid("dbe61b00-89ef-493c-8930-9d41a402a987"),
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            MinWeight = 0,
                            Value = 10m
                        },
                        new
                        {
                            Id = new Guid("d77e853d-e3bc-4279-ba8b-2fcd323be8a6"),
                            DistrictId = new Guid("dbe61b00-89ef-493c-8930-9d41a402a987"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 101,
                            Value = 0.87m
                        },
                        new
                        {
                            Id = new Guid("0e56e6ad-8a3c-468d-9fe1-b56800009e0e"),
                            DistrictId = new Guid("dbe61b00-89ef-493c-8930-9d41a402a987"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 101,
                            Value = 1.46m
                        },
                        new
                        {
                            Id = new Guid("0836dfc5-2fe6-4c4c-b9d1-c9f8c125fd4c"),
                            DistrictId = new Guid("ccd6ecfe-c907-4777-96ad-40ab41b7ac06"),
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            MinWeight = 0,
                            Value = 10m
                        },
                        new
                        {
                            Id = new Guid("8cd46492-daab-464b-bdcb-b07eb5f2d80d"),
                            DistrictId = new Guid("ccd6ecfe-c907-4777-96ad-40ab41b7ac06"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 101,
                            Value = 0.87m
                        },
                        new
                        {
                            Id = new Guid("e6eecebf-7d9c-4174-af2e-41904e34659d"),
                            DistrictId = new Guid("ccd6ecfe-c907-4777-96ad-40ab41b7ac06"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 101,
                            Value = 1.46m
                        },
                        new
                        {
                            Id = new Guid("2cbb44f7-a3e3-4444-85a9-6f8baee54f34"),
                            DistrictId = new Guid("6d332a8f-0bcd-4b81-9c59-6965f4ab40ae"),
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            MinWeight = 0,
                            Value = 10m
                        },
                        new
                        {
                            Id = new Guid("0354c60e-e98b-4737-87bb-d1a7e1e9cad0"),
                            DistrictId = new Guid("6d332a8f-0bcd-4b81-9c59-6965f4ab40ae"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 101,
                            Value = 1.00m
                        },
                        new
                        {
                            Id = new Guid("34599025-c411-4817-95e2-163143f8b454"),
                            DistrictId = new Guid("6d332a8f-0bcd-4b81-9c59-6965f4ab40ae"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 101,
                            Value = 1.53m
                        },
                        new
                        {
                            Id = new Guid("13b013d7-6d5f-4c66-844e-b414986860e4"),
                            DistrictId = new Guid("76adc0f7-ac5d-43cd-9983-eae135865030"),
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            MinWeight = 0,
                            Value = 10m
                        },
                        new
                        {
                            Id = new Guid("05142a75-6616-4cf1-be2c-f6fb445b6f2a"),
                            DistrictId = new Guid("76adc0f7-ac5d-43cd-9983-eae135865030"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 101,
                            Value = 1.00m
                        },
                        new
                        {
                            Id = new Guid("e416aaca-9929-40f5-a416-6df4f76f9324"),
                            DistrictId = new Guid("76adc0f7-ac5d-43cd-9983-eae135865030"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 101,
                            Value = 1.53m
                        },
                        new
                        {
                            Id = new Guid("b35f90cd-ae8c-41d4-a151-62ec73b823f8"),
                            DistrictId = new Guid("80ff3e90-dcb9-4bc3-9590-e3a2c331a0ec"),
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            MinWeight = 0,
                            Value = 10m
                        },
                        new
                        {
                            Id = new Guid("756b8bf2-e482-41e6-9d72-db550170a89b"),
                            DistrictId = new Guid("80ff3e90-dcb9-4bc3-9590-e3a2c331a0ec"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 101,
                            Value = 1.00m
                        },
                        new
                        {
                            Id = new Guid("99ec253d-7d1a-4982-928b-eba975d5b219"),
                            DistrictId = new Guid("72516348-d8e7-4ce3-af4e-f97b77897f89"),
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            MinWeight = 0,
                            Value = 10m
                        },
                        new
                        {
                            Id = new Guid("a76fca0b-3eab-4f2c-8f63-be4c64006471"),
                            DistrictId = new Guid("72516348-d8e7-4ce3-af4e-f97b77897f89"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 101,
                            Value = 0.97m
                        },
                        new
                        {
                            Id = new Guid("f7c7c84a-1c4c-45e9-a237-0ba1da2371c3"),
                            DistrictId = new Guid("72516348-d8e7-4ce3-af4e-f97b77897f89"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 101,
                            Value = 1.53m
                        },
                        new
                        {
                            Id = new Guid("0e1d1b1e-e21e-4272-b579-a5a502e50375"),
                            DistrictId = new Guid("5f0411d9-fc63-4dd4-a03f-50c26f0829c6"),
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            MinWeight = 0,
                            Value = 10m
                        },
                        new
                        {
                            Id = new Guid("2b48ae11-cb9c-4283-9e9f-b72e2eb8252d"),
                            DistrictId = new Guid("5f0411d9-fc63-4dd4-a03f-50c26f0829c6"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 101,
                            Value = 0.97m
                        },
                        new
                        {
                            Id = new Guid("89a37670-3d62-4416-9d6a-e94b0dc497a4"),
                            DistrictId = new Guid("5f0411d9-fc63-4dd4-a03f-50c26f0829c6"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 101,
                            Value = 1.53m
                        },
                        new
                        {
                            Id = new Guid("293ce448-5373-4321-8fca-8c823604fb34"),
                            DistrictId = new Guid("76e0d1b5-4fb7-4dc7-bcb1-1fadff9acc92"),
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            MinWeight = 0,
                            Value = 10m
                        },
                        new
                        {
                            Id = new Guid("893d3fcb-4560-49b8-97e2-6235ffb38092"),
                            DistrictId = new Guid("76e0d1b5-4fb7-4dc7-bcb1-1fadff9acc92"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 101,
                            Value = 0.97m
                        },
                        new
                        {
                            Id = new Guid("d0776b60-673d-4d3b-8f86-0f804bc9fd00"),
                            DistrictId = new Guid("76e0d1b5-4fb7-4dc7-bcb1-1fadff9acc92"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 101,
                            Value = 1.53m
                        },
                        new
                        {
                            Id = new Guid("b53e9f6f-82d9-44f2-b202-dac57caf01ab"),
                            DistrictId = new Guid("123a8e96-b5f2-4459-a896-da06599036cf"),
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            MinWeight = 0,
                            Value = 10m
                        },
                        new
                        {
                            Id = new Guid("2df3e7a7-24c2-4d96-a214-ac0fa639645b"),
                            DistrictId = new Guid("123a8e96-b5f2-4459-a896-da06599036cf"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 101,
                            Value = 1.17m
                        },
                        new
                        {
                            Id = new Guid("3c366b81-b961-4065-a618-efb80d70a046"),
                            DistrictId = new Guid("123a8e96-b5f2-4459-a896-da06599036cf"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 101,
                            Value = 1.61m
                        },
                        new
                        {
                            Id = new Guid("dc080b53-09df-4bc6-aa4f-d9f8e4552d5d"),
                            DistrictId = new Guid("98ead996-828c-4a6f-99c2-914b7c8110ef"),
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            MinWeight = 0,
                            Value = 10m
                        },
                        new
                        {
                            Id = new Guid("b0bf9db4-0594-4312-b15c-588340ebf6db"),
                            DistrictId = new Guid("98ead996-828c-4a6f-99c2-914b7c8110ef"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 101,
                            Value = 1.17m
                        },
                        new
                        {
                            Id = new Guid("9f32890b-7fda-49d9-bdd5-237ad67e3e39"),
                            DistrictId = new Guid("98ead996-828c-4a6f-99c2-914b7c8110ef"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 101,
                            Value = 1.61m
                        },
                        new
                        {
                            Id = new Guid("f77796bb-59f7-4c04-872b-f73d9246e10b"),
                            DistrictId = new Guid("5abcb711-259a-48dc-9817-2e5b988d690a"),
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            MinWeight = 0,
                            Value = 10m
                        },
                        new
                        {
                            Id = new Guid("b73662ca-13b9-4d0e-8006-e693168ce6d6"),
                            DistrictId = new Guid("5abcb711-259a-48dc-9817-2e5b988d690a"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 101,
                            Value = 1.17m
                        },
                        new
                        {
                            Id = new Guid("ac347d77-efbb-49b4-9763-3744668bc7c3"),
                            DistrictId = new Guid("5abcb711-259a-48dc-9817-2e5b988d690a"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 101,
                            Value = 1.61m
                        },
                        new
                        {
                            Id = new Guid("8779d940-0660-4c30-bf80-6d90bab9f630"),
                            DistrictId = new Guid("b90943d8-f764-42d3-8fca-da1ba2378634"),
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            MinWeight = 0,
                            Value = 10m
                        },
                        new
                        {
                            Id = new Guid("6cf0c56f-5235-432d-a5a7-a983623d9a40"),
                            DistrictId = new Guid("b90943d8-f764-42d3-8fca-da1ba2378634"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 101,
                            Value = 1.17m
                        },
                        new
                        {
                            Id = new Guid("75f2ba2f-7d34-43cd-8993-2a0402ce276a"),
                            DistrictId = new Guid("b90943d8-f764-42d3-8fca-da1ba2378634"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 101,
                            Value = 1.61m
                        },
                        new
                        {
                            Id = new Guid("fa1daec2-2ceb-4064-88d0-656923255fa9"),
                            DistrictId = new Guid("6d63584c-813f-48de-9b19-df143f83d2f7"),
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            MinWeight = 0,
                            Value = 10m
                        },
                        new
                        {
                            Id = new Guid("a229589a-5dbb-42b9-979f-da391e902aeb"),
                            DistrictId = new Guid("6d63584c-813f-48de-9b19-df143f83d2f7"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 101,
                            Value = 1.17m
                        },
                        new
                        {
                            Id = new Guid("e05606f6-e331-4cd7-aedd-b9d226cc9804"),
                            DistrictId = new Guid("6d63584c-813f-48de-9b19-df143f83d2f7"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 101,
                            Value = 1.61m
                        },
                        new
                        {
                            Id = new Guid("6cd64291-e078-4794-a75b-81af9445cc56"),
                            DistrictId = new Guid("d484cf5d-d07d-4e01-8aa4-c87747fa68fe"),
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            MinWeight = 0,
                            Value = 10m
                        },
                        new
                        {
                            Id = new Guid("141bf663-21a9-4c45-8821-8758c3995a56"),
                            DistrictId = new Guid("d484cf5d-d07d-4e01-8aa4-c87747fa68fe"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 101,
                            Value = 1.40m
                        },
                        new
                        {
                            Id = new Guid("ec4fc7ef-7f5f-42fc-b157-2e5b1b20a987"),
                            DistrictId = new Guid("d484cf5d-d07d-4e01-8aa4-c87747fa68fe"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 101,
                            Value = 1.92m
                        },
                        new
                        {
                            Id = new Guid("47bb681f-a2ba-4ed2-80bc-f2e0eac944dc"),
                            DistrictId = new Guid("05bb9082-20a8-4114-946b-cce72cedab19"),
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            MinWeight = 0,
                            Value = 10m
                        },
                        new
                        {
                            Id = new Guid("2c815f10-4889-4fe7-9b8f-302df4b54ef7"),
                            DistrictId = new Guid("05bb9082-20a8-4114-946b-cce72cedab19"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 23,
                            Value = 2.84m
                        },
                        new
                        {
                            Id = new Guid("d4d4380b-88f8-4acf-9ab3-bc9bdfe977e7"),
                            DistrictId = new Guid("05bb9082-20a8-4114-946b-cce72cedab19"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 71,
                            Value = 2.70m
                        },
                        new
                        {
                            Id = new Guid("11a76692-3ef0-4880-baf5-275ed2b8939c"),
                            DistrictId = new Guid("05bb9082-20a8-4114-946b-cce72cedab19"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 101,
                            Value = 2.06m
                        },
                        new
                        {
                            Id = new Guid("72d9e32d-45bf-4d06-b6ec-9dad1f5e15dc"),
                            DistrictId = new Guid("05bb9082-20a8-4114-946b-cce72cedab19"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 301,
                            Value = 1.98m
                        },
                        new
                        {
                            Id = new Guid("c4d67ff3-f669-46ea-952f-f0b6fd794dc1"),
                            DistrictId = new Guid("05bb9082-20a8-4114-946b-cce72cedab19"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 1501,
                            Value = 1.95m
                        },
                        new
                        {
                            Id = new Guid("bf661233-44b2-4846-8dbc-df3b58ffbffb"),
                            DistrictId = new Guid("0c02aa0a-b0d4-477a-b4e9-0a5073d323bf"),
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            MinWeight = 0,
                            Value = 10m
                        },
                        new
                        {
                            Id = new Guid("da4cfe87-5c52-404b-8a27-ba1bc6bf14dd"),
                            DistrictId = new Guid("0c02aa0a-b0d4-477a-b4e9-0a5073d323bf"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 23,
                            Value = 2.70m
                        },
                        new
                        {
                            Id = new Guid("4a51bb9b-e3ce-4448-b56e-a10c1c1570f0"),
                            DistrictId = new Guid("0c02aa0a-b0d4-477a-b4e9-0a5073d323bf"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 71,
                            Value = 2.55m
                        },
                        new
                        {
                            Id = new Guid("d313bae5-ae3f-4d82-9c0e-896497ed9613"),
                            DistrictId = new Guid("0c02aa0a-b0d4-477a-b4e9-0a5073d323bf"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 101,
                            Value = 1.90m
                        },
                        new
                        {
                            Id = new Guid("46d4bb73-9011-45e5-820a-11945177d76e"),
                            DistrictId = new Guid("0c02aa0a-b0d4-477a-b4e9-0a5073d323bf"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 301,
                            Value = 1.83m
                        },
                        new
                        {
                            Id = new Guid("b094f911-608e-4140-a2c5-b75fc1db436a"),
                            DistrictId = new Guid("0c02aa0a-b0d4-477a-b4e9-0a5073d323bf"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 1501,
                            Value = 1.80m
                        },
                        new
                        {
                            Id = new Guid("7d0d6678-ef77-4072-877a-f79a5fe3c04c"),
                            DistrictId = new Guid("34e425db-ff6c-4ab7-ac14-a1bd7a7c94a8"),
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            MinWeight = 0,
                            Value = 10m
                        },
                        new
                        {
                            Id = new Guid("dda8f797-541f-4b30-aa54-50c6d7a25f9b"),
                            DistrictId = new Guid("34e425db-ff6c-4ab7-ac14-a1bd7a7c94a8"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 23,
                            Value = 2.55m
                        },
                        new
                        {
                            Id = new Guid("d15fdc98-5b49-4285-88da-e874bba25337"),
                            DistrictId = new Guid("34e425db-ff6c-4ab7-ac14-a1bd7a7c94a8"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 71,
                            Value = 2.41m
                        },
                        new
                        {
                            Id = new Guid("7937e151-e873-4337-9345-184121c09816"),
                            DistrictId = new Guid("34e425db-ff6c-4ab7-ac14-a1bd7a7c94a8"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 101,
                            Value = 1.76m
                        },
                        new
                        {
                            Id = new Guid("a1f015c1-1c1e-4732-a1de-2adaea06855a"),
                            DistrictId = new Guid("34e425db-ff6c-4ab7-ac14-a1bd7a7c94a8"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 301,
                            Value = 1.69m
                        },
                        new
                        {
                            Id = new Guid("f89e5998-3f2b-4ad2-ab7f-1775923073b5"),
                            DistrictId = new Guid("34e425db-ff6c-4ab7-ac14-a1bd7a7c94a8"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 1501,
                            Value = 1.66m
                        });
                });

            modelBuilder.Entity("ShipbuData.TransportMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NameTr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TransportMethods");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            Enabled = true,
                            NameEn = "Air",
                            NameTr = "Uçak"
                        },
                        new
                        {
                            Id = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            Enabled = true,
                            NameEn = "Sea Slow",
                            NameTr = "Yavaş Gemi"
                        },
                        new
                        {
                            Id = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            Enabled = true,
                            NameEn = "Sea Fast",
                            NameTr = "Hızlı Gemi"
                        },
                        new
                        {
                            Id = new Guid("730cd01e-fb25-4347-8932-2b4056252e73"),
                            Enabled = true,
                            NameEn = "Fast Vessel",
                            NameTr = "Speed Boat"
                        },
                        new
                        {
                            Id = new Guid("af3e3b1a-06d9-413f-99ad-3378458be832"),
                            Enabled = true,
                            NameEn = "Truck",
                            NameTr = "TIR"
                        },
                        new
                        {
                            Id = new Guid("a5fe9692-ef46-4376-919f-43aeaa0c07a0"),
                            Enabled = true,
                            NameEn = "Railway",
                            NameTr = "Tren"
                        });
                });

            modelBuilder.Entity("ShipbuData.TransportOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TransportOrders");
                });

            modelBuilder.Entity("ShipbuData.TransportOrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("varchar(34)");

                    b.Property<bool>("HasAddress")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("TransportOrderId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TransportOrderId");

                    b.ToTable("TransportOrderItems");

                    b.HasDiscriminator<string>("Discriminator").HasValue("TransportOrderItem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ShipbuData.TransportOrderItemContainerType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NameTr")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("NameTr")
                        .IsUnique();

                    b.ToTable("TransportOrderItemContainerTypes");
                });

            modelBuilder.Entity("ShipbuData.TransportOrderItemFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AttachmentDescriptionEn")
                        .HasColumnType("longtext");

                    b.Property<string>("AttachmentDescriptionTr")
                        .HasColumnType("longtext");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DescriptionTr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NameTr")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NameEn")
                        .IsUnique();

                    b.HasIndex("NameTr")
                        .IsUnique();

                    b.ToTable("TransportOrderItemFeatures");
                });

            modelBuilder.Entity("ShipbuData.TransportOrderItemFeatureValue", b =>
                {
                    b.Property<Guid>("TransportOrderItemFeatureId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TransportOrderItemId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Attachment")
                        .HasColumnType("longtext");

                    b.HasKey("TransportOrderItemFeatureId", "TransportOrderItemId");

                    b.HasIndex("TransportOrderItemId");

                    b.ToTable("TransportOrderItemFeatureValue");
                });

            modelBuilder.Entity("ShipbuData.TransportRegion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDestination")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsOrigin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NameTr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TransportRegions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c194434c-7a4d-4d70-98df-1ecc78a333aa"),
                            Enabled = true,
                            IsDestination = true,
                            IsOrigin = false,
                            NameEn = "USA",
                            NameTr = "ABD"
                        },
                        new
                        {
                            Id = new Guid("aaaa0d64-abd7-4e96-aa49-35d4253e014f"),
                            Enabled = true,
                            IsDestination = true,
                            IsOrigin = false,
                            NameEn = "Canada",
                            NameTr = "Kanada"
                        },
                        new
                        {
                            Id = new Guid("5d751653-be94-44f4-afbe-5baf410ae321"),
                            Enabled = true,
                            IsDestination = true,
                            IsOrigin = false,
                            NameEn = "UK",
                            NameTr = "İngiltere"
                        },
                        new
                        {
                            Id = new Guid("39887e51-8a46-42c1-b621-699d96326883"),
                            Enabled = true,
                            IsDestination = true,
                            IsOrigin = false,
                            NameEn = "Europe",
                            NameTr = "Avrupa"
                        },
                        new
                        {
                            Id = new Guid("a524039f-30f6-4adf-8cd3-2e0859fd08ab"),
                            Enabled = true,
                            IsDestination = false,
                            IsOrigin = true,
                            NameEn = "China",
                            NameTr = "Çin"
                        });
                });

            modelBuilder.Entity("ShipbuData.TransportRegionMethod", b =>
                {
                    b.Property<Guid>("MethodId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("ETAMax")
                        .HasColumnType("int");

                    b.Property<int?>("ETAMin")
                        .HasColumnType("int");

                    b.Property<int>("Volume")
                        .HasColumnType("int");

                    b.HasKey("MethodId", "RegionId");

                    b.HasIndex("RegionId");

                    b.ToTable("TransportRegionMethod");

                    b.HasData(
                        new
                        {
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            RegionId = new Guid("c194434c-7a4d-4d70-98df-1ecc78a333aa"),
                            ETAMax = 5,
                            ETAMin = 3,
                            Volume = 6000
                        },
                        new
                        {
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            RegionId = new Guid("c194434c-7a4d-4d70-98df-1ecc78a333aa"),
                            ETAMax = 5,
                            ETAMin = 3,
                            Volume = 6000
                        },
                        new
                        {
                            MethodId = new Guid("730cd01e-fb25-4347-8932-2b4056252e73"),
                            RegionId = new Guid("c194434c-7a4d-4d70-98df-1ecc78a333aa"),
                            ETAMax = 5,
                            ETAMin = 3,
                            Volume = 6000
                        },
                        new
                        {
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            RegionId = new Guid("aaaa0d64-abd7-4e96-aa49-35d4253e014f"),
                            ETAMax = 5,
                            ETAMin = 3,
                            Volume = 6000
                        },
                        new
                        {
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            RegionId = new Guid("aaaa0d64-abd7-4e96-aa49-35d4253e014f"),
                            ETAMax = 5,
                            ETAMin = 3,
                            Volume = 6000
                        },
                        new
                        {
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            RegionId = new Guid("aaaa0d64-abd7-4e96-aa49-35d4253e014f"),
                            ETAMax = 5,
                            ETAMin = 3,
                            Volume = 6000
                        },
                        new
                        {
                            MethodId = new Guid("730cd01e-fb25-4347-8932-2b4056252e73"),
                            RegionId = new Guid("aaaa0d64-abd7-4e96-aa49-35d4253e014f"),
                            ETAMax = 5,
                            ETAMin = 3,
                            Volume = 6000
                        },
                        new
                        {
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            RegionId = new Guid("5d751653-be94-44f4-afbe-5baf410ae321"),
                            ETAMax = 5,
                            ETAMin = 3,
                            Volume = 6000
                        },
                        new
                        {
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            RegionId = new Guid("5d751653-be94-44f4-afbe-5baf410ae321"),
                            ETAMax = 5,
                            ETAMin = 3,
                            Volume = 6000
                        },
                        new
                        {
                            MethodId = new Guid("af3e3b1a-06d9-413f-99ad-3378458be832"),
                            RegionId = new Guid("5d751653-be94-44f4-afbe-5baf410ae321"),
                            ETAMax = 5,
                            ETAMin = 3,
                            Volume = 6000
                        },
                        new
                        {
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883"),
                            ETAMax = 5,
                            ETAMin = 3,
                            Volume = 6000
                        },
                        new
                        {
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883"),
                            ETAMax = 5,
                            ETAMin = 3,
                            Volume = 6000
                        },
                        new
                        {
                            MethodId = new Guid("a5fe9692-ef46-4376-919f-43aeaa0c07a0"),
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883"),
                            ETAMax = 5,
                            ETAMin = 3,
                            Volume = 6000
                        },
                        new
                        {
                            MethodId = new Guid("af3e3b1a-06d9-413f-99ad-3378458be832"),
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883"),
                            ETAMax = 5,
                            ETAMin = 3,
                            Volume = 6000
                        });
                });

            modelBuilder.Entity("ShipbuData.TransportStaticPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ContentEn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ContentTr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LabelEn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LabelTr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Views")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TransportStaticPages");
                });

            modelBuilder.Entity("ShipbuData.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("RefreshToken")
                        .HasColumnType("char(36)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("TransportOrderItemTransportOrderItemFeature", b =>
                {
                    b.Property<Guid>("TransportOrderItemFeaturesId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TransportOrderItemsId")
                        .HasColumnType("char(36)");

                    b.HasKey("TransportOrderItemFeaturesId", "TransportOrderItemsId");

                    b.HasIndex("TransportOrderItemsId");

                    b.ToTable("TransportOrderItemTransportOrderItemFeature");
                });

            modelBuilder.Entity("ShipbuData.TransportOrderItemContainer", b =>
                {
                    b.HasBaseType("ShipbuData.TransportOrderItem");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("TransportOrderItemContainerTypeId")
                        .HasColumnType("char(36)");

                    b.Property<float>("Weight")
                        .HasColumnType("float");

                    b.HasIndex("TransportOrderItemContainerTypeId");

                    b.HasDiscriminator().HasValue("TransportOrderItemContainer");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("ShipbuData.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("ShipbuData.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("ShipbuData.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("ShipbuData.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShipbuData.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("ShipbuData.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShipbuData.TransportDistrict", b =>
                {
                    b.HasOne("ShipbuData.TransportRegion", "Region")
                        .WithMany("Districts")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("ShipbuData.TransportFee", b =>
                {
                    b.HasOne("ShipbuData.TransportDistrict", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShipbuData.TransportMethod", "Method")
                        .WithMany()
                        .HasForeignKey("MethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");

                    b.Navigation("Method");
                });

            modelBuilder.Entity("ShipbuData.TransportOrder", b =>
                {
                    b.HasOne("ShipbuData.User", "User")
                        .WithMany("TransportOrders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShipbuData.TransportOrderItem", b =>
                {
                    b.HasOne("ShipbuData.TransportOrder", "TransportOrder")
                        .WithMany("TransportOrderItems")
                        .HasForeignKey("TransportOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransportOrder");
                });

            modelBuilder.Entity("ShipbuData.TransportOrderItemFeatureValue", b =>
                {
                    b.HasOne("ShipbuData.TransportOrderItemFeature", "TransportOrderItemFeature")
                        .WithMany("TransportOrderItemFeatureValues")
                        .HasForeignKey("TransportOrderItemFeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShipbuData.TransportOrderItem", "TransportOrderItem")
                        .WithMany("TransportOrderItemFeatureValues")
                        .HasForeignKey("TransportOrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransportOrderItem");

                    b.Navigation("TransportOrderItemFeature");
                });

            modelBuilder.Entity("ShipbuData.TransportRegionMethod", b =>
                {
                    b.HasOne("ShipbuData.TransportMethod", "Method")
                        .WithMany("TransportRegionMethods")
                        .HasForeignKey("MethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShipbuData.TransportRegion", "Region")
                        .WithMany("TransportRegionMethods")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Method");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("TransportOrderItemTransportOrderItemFeature", b =>
                {
                    b.HasOne("ShipbuData.TransportOrderItemFeature", null)
                        .WithMany()
                        .HasForeignKey("TransportOrderItemFeaturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShipbuData.TransportOrderItem", null)
                        .WithMany()
                        .HasForeignKey("TransportOrderItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TransportOrderItemTransportOrderItemFeature_TransportOrderI~1");
                });

            modelBuilder.Entity("ShipbuData.TransportOrderItemContainer", b =>
                {
                    b.HasOne("ShipbuData.TransportOrderItemContainerType", "TransportOrderItemContainerType")
                        .WithMany("TransportOrderItemContainers")
                        .HasForeignKey("TransportOrderItemContainerTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TransportOrderItemContainerType");
                });

            modelBuilder.Entity("ShipbuData.TransportMethod", b =>
                {
                    b.Navigation("TransportRegionMethods");
                });

            modelBuilder.Entity("ShipbuData.TransportOrder", b =>
                {
                    b.Navigation("TransportOrderItems");
                });

            modelBuilder.Entity("ShipbuData.TransportOrderItem", b =>
                {
                    b.Navigation("TransportOrderItemFeatureValues");
                });

            modelBuilder.Entity("ShipbuData.TransportOrderItemContainerType", b =>
                {
                    b.Navigation("TransportOrderItemContainers");
                });

            modelBuilder.Entity("ShipbuData.TransportOrderItemFeature", b =>
                {
                    b.Navigation("TransportOrderItemFeatureValues");
                });

            modelBuilder.Entity("ShipbuData.TransportRegion", b =>
                {
                    b.Navigation("Districts");

                    b.Navigation("TransportRegionMethods");
                });

            modelBuilder.Entity("ShipbuData.User", b =>
                {
                    b.Navigation("TransportOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
