// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShipbuData;

#nullable disable

namespace MigrationsMySQL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240111163039_OrderItemAddress")]
    partial class OrderItemAddress
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ShipbuData.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("ShipbuData.TransportAcademyVideo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("DescriptionEn")
                        .HasColumnType("longtext");

                    b.Property<string>("DescriptionTr")
                        .HasColumnType("longtext");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2048)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NameTr")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("NameTr")
                        .IsUnique();

                    b.ToTable("TransportAcademyVideos");
                });

            modelBuilder.Entity("ShipbuData.TransportDistrict", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsAmazonDepot")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NameTr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("TransportDistricts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("05bb9082-20a8-4114-946b-cce72cedab19"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Eastern USA",
                            NameTr = "Doğu Amerika",
                            RegionId = new Guid("c194434c-7a4d-4d70-98df-1ecc78a333aa")
                        },
                        new
                        {
                            Id = new Guid("0c02aa0a-b0d4-477a-b4e9-0a5073d323bf"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Central USA",
                            NameTr = "Merkez Amerika",
                            RegionId = new Guid("c194434c-7a4d-4d70-98df-1ecc78a333aa")
                        },
                        new
                        {
                            Id = new Guid("34e425db-ff6c-4ab7-ac14-a1bd7a7c94a8"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Western USA",
                            NameTr = "Batı Amerika",
                            RegionId = new Guid("c194434c-7a4d-4d70-98df-1ecc78a333aa")
                        },
                        new
                        {
                            Id = new Guid("2b26b58b-050c-46a7-8567-2325c31fa6fb"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "ONT8",
                            NameTr = "ONT8",
                            RegionId = new Guid("c194434c-7a4d-4d70-98df-1ecc78a333aa")
                        },
                        new
                        {
                            Id = new Guid("3bf2da8a-0a2c-4a8f-99c9-35742cb7fa2e"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "LGB8",
                            NameTr = "LGB8",
                            RegionId = new Guid("c194434c-7a4d-4d70-98df-1ecc78a333aa")
                        },
                        new
                        {
                            Id = new Guid("dbe61b00-89ef-493c-8930-9d41a402a987"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "LAX9",
                            NameTr = "LAX9",
                            RegionId = new Guid("c194434c-7a4d-4d70-98df-1ecc78a333aa")
                        },
                        new
                        {
                            Id = new Guid("ccd6ecfe-c907-4777-96ad-40ab41b7ac06"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "SBD1",
                            NameTr = "SBD1",
                            RegionId = new Guid("c194434c-7a4d-4d70-98df-1ecc78a333aa")
                        },
                        new
                        {
                            Id = new Guid("6d332a8f-0bcd-4b81-9c59-6965f4ab40ae"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "SCK4",
                            NameTr = "SCK4",
                            RegionId = new Guid("c194434c-7a4d-4d70-98df-1ecc78a333aa")
                        },
                        new
                        {
                            Id = new Guid("76adc0f7-ac5d-43cd-9983-eae135865030"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "SMF3",
                            NameTr = "SMF3",
                            RegionId = new Guid("c194434c-7a4d-4d70-98df-1ecc78a333aa")
                        },
                        new
                        {
                            Id = new Guid("80ff3e90-dcb9-4bc3-9590-e3a2c331a0ec"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "VGT3",
                            NameTr = "VGT2",
                            RegionId = new Guid("c194434c-7a4d-4d70-98df-1ecc78a333aa")
                        },
                        new
                        {
                            Id = new Guid("72516348-d8e7-4ce3-af4e-f97b77897f89"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "GYR2",
                            NameTr = "GYR2",
                            RegionId = new Guid("c194434c-7a4d-4d70-98df-1ecc78a333aa")
                        },
                        new
                        {
                            Id = new Guid("5f0411d9-fc63-4dd4-a03f-50c26f0829c6"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "GYR3",
                            NameTr = "GYR3",
                            RegionId = new Guid("c194434c-7a4d-4d70-98df-1ecc78a333aa")
                        },
                        new
                        {
                            Id = new Guid("76e0d1b5-4fb7-4dc7-bcb1-1fadff9acc92"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "LAS1",
                            NameTr = "LAS1",
                            RegionId = new Guid("c194434c-7a4d-4d70-98df-1ecc78a333aa")
                        },
                        new
                        {
                            Id = new Guid("123a8e96-b5f2-4459-a896-da06599036cf"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "SJC7",
                            NameTr = "SJC7",
                            RegionId = new Guid("c194434c-7a4d-4d70-98df-1ecc78a333aa")
                        },
                        new
                        {
                            Id = new Guid("98ead996-828c-4a6f-99c2-914b7c8110ef"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "KRB1",
                            NameTr = "KRB1",
                            RegionId = new Guid("c194434c-7a4d-4d70-98df-1ecc78a333aa")
                        },
                        new
                        {
                            Id = new Guid("5abcb711-259a-48dc-9817-2e5b988d690a"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "KRB4",
                            NameTr = "KRB4",
                            RegionId = new Guid("c194434c-7a4d-4d70-98df-1ecc78a333aa")
                        },
                        new
                        {
                            Id = new Guid("b90943d8-f764-42d3-8fca-da1ba2378634"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "SBD2",
                            NameTr = "SBD2",
                            RegionId = new Guid("c194434c-7a4d-4d70-98df-1ecc78a333aa")
                        },
                        new
                        {
                            Id = new Guid("6d63584c-813f-48de-9b19-df143f83d2f7"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "SBD3",
                            NameTr = "SBD3",
                            RegionId = new Guid("c194434c-7a4d-4d70-98df-1ecc78a333aa")
                        },
                        new
                        {
                            Id = new Guid("d484cf5d-d07d-4e01-8aa4-c87747fa68fe"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "FTW1",
                            NameTr = "FTW1",
                            RegionId = new Guid("c194434c-7a4d-4d70-98df-1ecc78a333aa")
                        },
                        new
                        {
                            Id = new Guid("573da713-55b6-4505-9bb0-1e033f7c47e5"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "Vancouver YVR",
                            NameTr = "Vancouver YVR",
                            RegionId = new Guid("aaaa0d64-abd7-4e96-aa49-35d4253e014f")
                        },
                        new
                        {
                            Id = new Guid("637a3cf8-e91a-4e46-8ccf-d1bfcbaa19e3"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "Calgary YYC",
                            NameTr = "Calgary YYC",
                            RegionId = new Guid("aaaa0d64-abd7-4e96-aa49-35d4253e014f")
                        },
                        new
                        {
                            Id = new Guid("82060812-b989-4340-bd2e-8840585a8acf"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "Calgary YEG",
                            NameTr = "Calgary YEG",
                            RegionId = new Guid("aaaa0d64-abd7-4e96-aa49-35d4253e014f")
                        },
                        new
                        {
                            Id = new Guid("545149ad-862b-4e00-a5d6-e3492d68463b"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "Toronto YYZ",
                            NameTr = "Toronto YYZ",
                            RegionId = new Guid("aaaa0d64-abd7-4e96-aa49-35d4253e014f")
                        },
                        new
                        {
                            Id = new Guid("829f6814-b1a3-43f0-8d71-f2ea928e743b"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "Ottawa YOW",
                            NameTr = "Ottawa YOW",
                            RegionId = new Guid("aaaa0d64-abd7-4e96-aa49-35d4253e014f")
                        },
                        new
                        {
                            Id = new Guid("ff9e1ee3-91cc-404f-ae3f-4a4c8ad891f7"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "Ottawa YUL",
                            NameTr = "Ottawa YUL",
                            RegionId = new Guid("aaaa0d64-abd7-4e96-aa49-35d4253e014f")
                        },
                        new
                        {
                            Id = new Guid("431d73fb-827d-43c2-8ee3-98568d1cfcf8"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Bussiness Private Address",
                            NameTr = "Kurumsal/Bireysel Adres",
                            RegionId = new Guid("aaaa0d64-abd7-4e96-aa49-35d4253e014f")
                        },
                        new
                        {
                            Id = new Guid("9495dd9f-53c2-41c5-8680-34539a483a42"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "Edmonton YEG1",
                            NameTr = "Edmonton YEG1",
                            RegionId = new Guid("aaaa0d64-abd7-4e96-aa49-35d4253e014f")
                        },
                        new
                        {
                            Id = new Guid("de1cfc73-52a1-4c72-aed7-1c67a588e436"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "Toronto YOO",
                            NameTr = "Toronto YOO",
                            RegionId = new Guid("aaaa0d64-abd7-4e96-aa49-35d4253e014f")
                        },
                        new
                        {
                            Id = new Guid("bb88a4e3-a99f-45e4-a753-cb430b608a4f"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "Toronto YHM",
                            NameTr = "Toronto YHM",
                            RegionId = new Guid("aaaa0d64-abd7-4e96-aa49-35d4253e014f")
                        },
                        new
                        {
                            Id = new Guid("a42ea92c-d563-4eb8-bd25-83a3ac1217dc"),
                            Enabled = true,
                            IsAmazonDepot = true,
                            NameEn = "Vancouver YXX",
                            NameTr = "Vancouver YXX",
                            RegionId = new Guid("aaaa0d64-abd7-4e96-aa49-35d4253e014f")
                        },
                        new
                        {
                            Id = new Guid("e7a610f5-1fe9-41e2-8493-34424d982b9b"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "UK",
                            NameTr = "İngiltere",
                            RegionId = new Guid("5d751653-be94-44f4-afbe-5baf410ae321")
                        },
                        new
                        {
                            Id = new Guid("cb7fa78d-6de7-4838-9e54-c279bea798b0"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Germany",
                            NameTr = "Almanya",
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883")
                        },
                        new
                        {
                            Id = new Guid("78587899-2653-4be7-b07e-13a7596d5649"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "France",
                            NameTr = "Fransa",
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883")
                        },
                        new
                        {
                            Id = new Guid("e1371a95-daa6-4c22-8bcd-c86e5ee03203"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Poland",
                            NameTr = "Polonya",
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883")
                        },
                        new
                        {
                            Id = new Guid("cb39b0c9-34bb-4f55-a39b-a575aff157b2"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Czech Rep.",
                            NameTr = "Çekya",
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883")
                        },
                        new
                        {
                            Id = new Guid("660348c5-b814-42bf-a1b9-df56696f3c75"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Belgium",
                            NameTr = "Belçika",
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883")
                        },
                        new
                        {
                            Id = new Guid("38df3f9b-f88b-4c6d-9a36-76fe0d3e1792"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Austria",
                            NameTr = "Avusturya",
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883")
                        },
                        new
                        {
                            Id = new Guid("8603813c-d724-4d63-8013-c273c9fe5fbc"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Luxembourg",
                            NameTr = "Lüksemburg",
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883")
                        },
                        new
                        {
                            Id = new Guid("7ddb170b-5696-4abe-a5a8-b6424a966ba9"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Spain",
                            NameTr = "İspanya",
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883")
                        },
                        new
                        {
                            Id = new Guid("8b08542b-6c77-4d8e-8d54-329ceec6c1e1"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Italy",
                            NameTr = "İtalya",
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883")
                        },
                        new
                        {
                            Id = new Guid("52e63491-43b4-47cc-b53e-8384aac7c07c"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Netherlands",
                            NameTr = "Hollanda",
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883")
                        },
                        new
                        {
                            Id = new Guid("58a45e41-a7fe-4dec-9a8e-3bbf38455e5f"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Greece",
                            NameTr = "Yunanistan",
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883")
                        },
                        new
                        {
                            Id = new Guid("ee896fe1-1434-4136-a70e-d2c9fa49d902"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Denmark",
                            NameTr = "Danimarka",
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883")
                        },
                        new
                        {
                            Id = new Guid("3c4fedcc-eaeb-4480-8574-c759e9aa2f9d"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Sweden",
                            NameTr = "İsveç",
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883")
                        },
                        new
                        {
                            Id = new Guid("da5d4f5e-79ac-4b69-b0f5-cf027053ec8c"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Finland",
                            NameTr = "Fillandiya",
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883")
                        },
                        new
                        {
                            Id = new Guid("bc3767bc-68d7-400d-ae61-707fc3bb5878"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Slovakia",
                            NameTr = "Slovakya",
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883")
                        },
                        new
                        {
                            Id = new Guid("291c8b1e-1eb6-4bc0-b714-86e79ed31316"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Slovenia",
                            NameTr = "Slovenya",
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883")
                        },
                        new
                        {
                            Id = new Guid("6de69db5-e0a5-4fe3-95a9-df3721f50d0b"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Hungary",
                            NameTr = "Macaristan",
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883")
                        },
                        new
                        {
                            Id = new Guid("e7b21a66-1c15-49cf-9ff9-c8b3455ba57d"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Portugal",
                            NameTr = "Portekiz",
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883")
                        },
                        new
                        {
                            Id = new Guid("e7777c20-3abb-4a39-af05-11fcee8f7534"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Croatia",
                            NameTr = "Hırvatistan",
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883")
                        },
                        new
                        {
                            Id = new Guid("b93226d5-2642-4705-99ca-734af02c624b"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Estonia",
                            NameTr = "Estonya",
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883")
                        },
                        new
                        {
                            Id = new Guid("da7b0a60-d6ca-44d4-9e28-d5d804cd7a64"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Latvia",
                            NameTr = "Latviya",
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883")
                        },
                        new
                        {
                            Id = new Guid("869993cb-ccd8-498f-880c-97f0e02f2846"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Bulgaria",
                            NameTr = "Bulgaristan",
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883")
                        },
                        new
                        {
                            Id = new Guid("18351822-a469-408c-b8a9-f17dbff1020a"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Monaco",
                            NameTr = "Monako",
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883")
                        },
                        new
                        {
                            Id = new Guid("803e5fb5-2a8f-4e42-a544-071b0b9fcecf"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Ireland",
                            NameTr = "Irlanda",
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883")
                        },
                        new
                        {
                            Id = new Guid("3a52e207-c517-49a2-98d4-2998f29f1ecd"),
                            Enabled = true,
                            IsAmazonDepot = false,
                            NameEn = "Romania",
                            NameTr = "Romanya",
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883")
                        });
                });

            modelBuilder.Entity("ShipbuData.TransportFee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DistrictId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MethodId")
                        .HasColumnType("char(36)");

                    b.Property<int>("MinWeight")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("MethodId");

                    b.ToTable("TransportFees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0a49f26b-3c5c-4914-b7a3-b533ff08c747"),
                            DistrictId = new Guid("05bb9082-20a8-4114-946b-cce72cedab19"),
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            MinWeight = 0,
                            Value = 10m
                        },
                        new
                        {
                            Id = new Guid("9f6a50f8-3bc4-425d-9378-6e56a720b2f9"),
                            DistrictId = new Guid("05bb9082-20a8-4114-946b-cce72cedab19"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 23,
                            Value = 2.37m
                        },
                        new
                        {
                            Id = new Guid("36b50892-fcda-44dd-87ee-e7526b9c318c"),
                            DistrictId = new Guid("05bb9082-20a8-4114-946b-cce72cedab19"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 71,
                            Value = 2.22m
                        },
                        new
                        {
                            Id = new Guid("c7238d9b-5e45-478f-9c7b-11feb8ac646c"),
                            DistrictId = new Guid("05bb9082-20a8-4114-946b-cce72cedab19"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 101,
                            Value = 1.57m
                        },
                        new
                        {
                            Id = new Guid("123da90d-6dda-4605-a755-c56ce7a2cf34"),
                            DistrictId = new Guid("05bb9082-20a8-4114-946b-cce72cedab19"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 301,
                            Value = 1.50m
                        },
                        new
                        {
                            Id = new Guid("0b31383f-0801-4e41-aa29-12e008784956"),
                            DistrictId = new Guid("05bb9082-20a8-4114-946b-cce72cedab19"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 1501,
                            Value = 1.47m
                        },
                        new
                        {
                            Id = new Guid("306680ea-8452-4082-b3f2-70a09a311340"),
                            DistrictId = new Guid("0c02aa0a-b0d4-477a-b4e9-0a5073d323bf"),
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            MinWeight = 0,
                            Value = 10m
                        },
                        new
                        {
                            Id = new Guid("2407409c-da79-4a42-a8f9-226d38e8b00c"),
                            DistrictId = new Guid("0c02aa0a-b0d4-477a-b4e9-0a5073d323bf"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 23,
                            Value = 2.22m
                        },
                        new
                        {
                            Id = new Guid("17bc576d-d493-4f8d-9039-c43ba14c9639"),
                            DistrictId = new Guid("0c02aa0a-b0d4-477a-b4e9-0a5073d323bf"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 71,
                            Value = 2.08m
                        },
                        new
                        {
                            Id = new Guid("4dde1261-07d5-4dc1-b12c-550aad64bf73"),
                            DistrictId = new Guid("0c02aa0a-b0d4-477a-b4e9-0a5073d323bf"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 101,
                            Value = 1.43m
                        },
                        new
                        {
                            Id = new Guid("325257c8-f124-4bbf-8860-4ac5af5e2b46"),
                            DistrictId = new Guid("0c02aa0a-b0d4-477a-b4e9-0a5073d323bf"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 301,
                            Value = 1.36m
                        },
                        new
                        {
                            Id = new Guid("7c1825ad-86db-4ec9-836a-6ec3091a1949"),
                            DistrictId = new Guid("0c02aa0a-b0d4-477a-b4e9-0a5073d323bf"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 1501,
                            Value = 1.33m
                        },
                        new
                        {
                            Id = new Guid("42bf1932-a2fd-4314-9b6a-403b0c150237"),
                            DistrictId = new Guid("34e425db-ff6c-4ab7-ac14-a1bd7a7c94a8"),
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            MinWeight = 0,
                            Value = 10m
                        },
                        new
                        {
                            Id = new Guid("624899fc-0018-485b-9797-1c2ca908cb13"),
                            DistrictId = new Guid("34e425db-ff6c-4ab7-ac14-a1bd7a7c94a8"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 23,
                            Value = 2.08m
                        },
                        new
                        {
                            Id = new Guid("80214f79-6d1c-47ef-911c-b08b1d0f175a"),
                            DistrictId = new Guid("34e425db-ff6c-4ab7-ac14-a1bd7a7c94a8"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 71,
                            Value = 1.93m
                        },
                        new
                        {
                            Id = new Guid("97ffc415-fc54-4d3f-bf14-14c6c6315361"),
                            DistrictId = new Guid("34e425db-ff6c-4ab7-ac14-a1bd7a7c94a8"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 101,
                            Value = 1.57m
                        },
                        new
                        {
                            Id = new Guid("e8b6f70f-02b6-4c43-9687-7ca575798d60"),
                            DistrictId = new Guid("34e425db-ff6c-4ab7-ac14-a1bd7a7c94a8"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 301,
                            Value = 1.82m
                        },
                        new
                        {
                            Id = new Guid("14bf28bf-6a8d-4afa-b29c-5a3f90c71a45"),
                            DistrictId = new Guid("34e425db-ff6c-4ab7-ac14-a1bd7a7c94a8"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 1501,
                            Value = 1.82m
                        },
                        new
                        {
                            Id = new Guid("febaa7f4-9d96-4788-924c-c5150b321683"),
                            DistrictId = new Guid("2b26b58b-050c-46a7-8567-2325c31fa6fb"),
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            MinWeight = 0,
                            Value = 10m
                        },
                        new
                        {
                            Id = new Guid("48e68cab-3e53-4d55-87ad-a67c90d5d460"),
                            DistrictId = new Guid("2b26b58b-050c-46a7-8567-2325c31fa6fb"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 101,
                            Value = 0.87m
                        },
                        new
                        {
                            Id = new Guid("95c35a77-81cf-409d-babd-001a8f8db1d5"),
                            DistrictId = new Guid("2b26b58b-050c-46a7-8567-2325c31fa6fb"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 101,
                            Value = 1.43m
                        },
                        new
                        {
                            Id = new Guid("b7c660e4-07ec-48dd-9d1c-501f8483c837"),
                            DistrictId = new Guid("3bf2da8a-0a2c-4a8f-99c9-35742cb7fa2e"),
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            MinWeight = 0,
                            Value = 10m
                        },
                        new
                        {
                            Id = new Guid("79c0d3ac-c0c4-422b-8dbf-59bad9f4f1e4"),
                            DistrictId = new Guid("3bf2da8a-0a2c-4a8f-99c9-35742cb7fa2e"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 101,
                            Value = 0.87m
                        },
                        new
                        {
                            Id = new Guid("6591ac05-a38b-478c-a53d-7b72bd14ac5b"),
                            DistrictId = new Guid("3bf2da8a-0a2c-4a8f-99c9-35742cb7fa2e"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 101,
                            Value = 1.46m
                        },
                        new
                        {
                            Id = new Guid("7ddd4b01-370b-435f-9d95-1f8db5d82687"),
                            DistrictId = new Guid("dbe61b00-89ef-493c-8930-9d41a402a987"),
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            MinWeight = 0,
                            Value = 10m
                        },
                        new
                        {
                            Id = new Guid("a01018cf-8145-4f7f-8a00-70eca36824d0"),
                            DistrictId = new Guid("dbe61b00-89ef-493c-8930-9d41a402a987"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 101,
                            Value = 0.87m
                        },
                        new
                        {
                            Id = new Guid("cb67929b-312b-47cc-b11b-aaaf489f9f23"),
                            DistrictId = new Guid("dbe61b00-89ef-493c-8930-9d41a402a987"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 101,
                            Value = 1.46m
                        },
                        new
                        {
                            Id = new Guid("530aab5e-afbe-4ed9-9865-bc674e43af5f"),
                            DistrictId = new Guid("ccd6ecfe-c907-4777-96ad-40ab41b7ac06"),
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            MinWeight = 0,
                            Value = 10m
                        },
                        new
                        {
                            Id = new Guid("2c3e0539-729d-4f2e-aacb-2c731d71b94d"),
                            DistrictId = new Guid("ccd6ecfe-c907-4777-96ad-40ab41b7ac06"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 101,
                            Value = 0.87m
                        },
                        new
                        {
                            Id = new Guid("2536cc99-c145-433e-9b80-95a18348428e"),
                            DistrictId = new Guid("ccd6ecfe-c907-4777-96ad-40ab41b7ac06"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 101,
                            Value = 1.46m
                        },
                        new
                        {
                            Id = new Guid("8612afcd-c62f-43d3-9e0a-3a0c55952553"),
                            DistrictId = new Guid("6d332a8f-0bcd-4b81-9c59-6965f4ab40ae"),
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            MinWeight = 0,
                            Value = 10m
                        },
                        new
                        {
                            Id = new Guid("6c204e5b-d2b0-4baa-93a8-d5fe759842f2"),
                            DistrictId = new Guid("6d332a8f-0bcd-4b81-9c59-6965f4ab40ae"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 101,
                            Value = 1.00m
                        },
                        new
                        {
                            Id = new Guid("64f9788f-eab4-41b3-8c88-a25010b49364"),
                            DistrictId = new Guid("6d332a8f-0bcd-4b81-9c59-6965f4ab40ae"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 101,
                            Value = 1.53m
                        },
                        new
                        {
                            Id = new Guid("5b94a26d-7508-4bd5-a74d-a45a0ff6a78f"),
                            DistrictId = new Guid("76adc0f7-ac5d-43cd-9983-eae135865030"),
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            MinWeight = 0,
                            Value = 10m
                        },
                        new
                        {
                            Id = new Guid("c600b80b-eee9-4ab8-b898-941817d20727"),
                            DistrictId = new Guid("76adc0f7-ac5d-43cd-9983-eae135865030"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 101,
                            Value = 1.00m
                        },
                        new
                        {
                            Id = new Guid("a3d9a3f1-1a22-4f60-b7e9-b2d9f772e86c"),
                            DistrictId = new Guid("76adc0f7-ac5d-43cd-9983-eae135865030"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 101,
                            Value = 1.53m
                        },
                        new
                        {
                            Id = new Guid("3eda579e-8d9a-40a2-8107-22c31638eb73"),
                            DistrictId = new Guid("80ff3e90-dcb9-4bc3-9590-e3a2c331a0ec"),
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            MinWeight = 0,
                            Value = 10m
                        },
                        new
                        {
                            Id = new Guid("92747c31-b7ef-4d61-98f5-9b4e13bc6b7e"),
                            DistrictId = new Guid("80ff3e90-dcb9-4bc3-9590-e3a2c331a0ec"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 101,
                            Value = 1.00m
                        },
                        new
                        {
                            Id = new Guid("a5df7a7a-96cf-4b47-b9c7-94854bfb8b64"),
                            DistrictId = new Guid("72516348-d8e7-4ce3-af4e-f97b77897f89"),
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            MinWeight = 0,
                            Value = 10m
                        },
                        new
                        {
                            Id = new Guid("cbd12487-f493-41fc-a2dc-f3b0094ec58d"),
                            DistrictId = new Guid("72516348-d8e7-4ce3-af4e-f97b77897f89"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 101,
                            Value = 0.97m
                        },
                        new
                        {
                            Id = new Guid("04f4a19b-f2d6-4a1f-9156-9920550d1536"),
                            DistrictId = new Guid("72516348-d8e7-4ce3-af4e-f97b77897f89"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 101,
                            Value = 1.53m
                        },
                        new
                        {
                            Id = new Guid("1d3fa72c-5ea8-4bc7-8ac0-612a8ec7a555"),
                            DistrictId = new Guid("5f0411d9-fc63-4dd4-a03f-50c26f0829c6"),
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            MinWeight = 0,
                            Value = 10m
                        },
                        new
                        {
                            Id = new Guid("460e932b-7789-4ae7-9cda-447cc6bedb27"),
                            DistrictId = new Guid("5f0411d9-fc63-4dd4-a03f-50c26f0829c6"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 101,
                            Value = 0.97m
                        },
                        new
                        {
                            Id = new Guid("de4abdce-5291-4d2c-8e1b-de2bc5600ad6"),
                            DistrictId = new Guid("5f0411d9-fc63-4dd4-a03f-50c26f0829c6"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 101,
                            Value = 1.53m
                        },
                        new
                        {
                            Id = new Guid("3dd07969-8070-4691-979a-97bdb202fc52"),
                            DistrictId = new Guid("76e0d1b5-4fb7-4dc7-bcb1-1fadff9acc92"),
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            MinWeight = 0,
                            Value = 10m
                        },
                        new
                        {
                            Id = new Guid("91687e45-1c97-429c-b724-9d3d557b0e70"),
                            DistrictId = new Guid("76e0d1b5-4fb7-4dc7-bcb1-1fadff9acc92"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 101,
                            Value = 0.97m
                        },
                        new
                        {
                            Id = new Guid("251c341f-c99b-4ee1-9627-4feb5d708143"),
                            DistrictId = new Guid("76e0d1b5-4fb7-4dc7-bcb1-1fadff9acc92"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 101,
                            Value = 1.53m
                        },
                        new
                        {
                            Id = new Guid("9ced8803-e76e-47d7-b17d-e17094a621d8"),
                            DistrictId = new Guid("123a8e96-b5f2-4459-a896-da06599036cf"),
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            MinWeight = 0,
                            Value = 10m
                        },
                        new
                        {
                            Id = new Guid("df9a606a-bda9-4256-bfb4-0eda4d8e2340"),
                            DistrictId = new Guid("123a8e96-b5f2-4459-a896-da06599036cf"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 101,
                            Value = 1.17m
                        },
                        new
                        {
                            Id = new Guid("6950ac32-20d5-45b5-85f5-b6f2b8d36449"),
                            DistrictId = new Guid("123a8e96-b5f2-4459-a896-da06599036cf"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 101,
                            Value = 1.61m
                        },
                        new
                        {
                            Id = new Guid("5fd30917-fb3e-4724-b747-20a276354e45"),
                            DistrictId = new Guid("98ead996-828c-4a6f-99c2-914b7c8110ef"),
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            MinWeight = 0,
                            Value = 10m
                        },
                        new
                        {
                            Id = new Guid("07e4e0d3-a768-46e1-bc3c-06801e509c31"),
                            DistrictId = new Guid("98ead996-828c-4a6f-99c2-914b7c8110ef"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 101,
                            Value = 1.17m
                        },
                        new
                        {
                            Id = new Guid("d7ba9058-0e5c-4708-9527-d787e06f9c0a"),
                            DistrictId = new Guid("98ead996-828c-4a6f-99c2-914b7c8110ef"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 101,
                            Value = 1.61m
                        },
                        new
                        {
                            Id = new Guid("15e424c5-a72f-4eb1-963c-ca5ae7141c83"),
                            DistrictId = new Guid("5abcb711-259a-48dc-9817-2e5b988d690a"),
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            MinWeight = 0,
                            Value = 10m
                        },
                        new
                        {
                            Id = new Guid("4a6c1973-bcd0-46a9-8d11-8234345276f6"),
                            DistrictId = new Guid("5abcb711-259a-48dc-9817-2e5b988d690a"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 101,
                            Value = 1.17m
                        },
                        new
                        {
                            Id = new Guid("fa367c8b-d8b8-4ae8-85f0-8b46febdda72"),
                            DistrictId = new Guid("5abcb711-259a-48dc-9817-2e5b988d690a"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 101,
                            Value = 1.61m
                        },
                        new
                        {
                            Id = new Guid("3a557b65-9869-4ab0-a9ac-649682e42ebc"),
                            DistrictId = new Guid("b90943d8-f764-42d3-8fca-da1ba2378634"),
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            MinWeight = 0,
                            Value = 10m
                        },
                        new
                        {
                            Id = new Guid("0005399a-6343-4c99-9069-254584a8c3ee"),
                            DistrictId = new Guid("b90943d8-f764-42d3-8fca-da1ba2378634"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 101,
                            Value = 1.17m
                        },
                        new
                        {
                            Id = new Guid("a2081584-ed77-4b21-a1d9-173d9dbbdf02"),
                            DistrictId = new Guid("b90943d8-f764-42d3-8fca-da1ba2378634"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 101,
                            Value = 1.61m
                        },
                        new
                        {
                            Id = new Guid("06fab812-9f40-45d8-ab2b-0703ab6c7055"),
                            DistrictId = new Guid("6d63584c-813f-48de-9b19-df143f83d2f7"),
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            MinWeight = 0,
                            Value = 10m
                        },
                        new
                        {
                            Id = new Guid("194af597-f8e9-4049-9231-9d9ddf7193ac"),
                            DistrictId = new Guid("6d63584c-813f-48de-9b19-df143f83d2f7"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 101,
                            Value = 1.17m
                        },
                        new
                        {
                            Id = new Guid("5d8c33c7-3c1f-4b36-b21a-f2c369758625"),
                            DistrictId = new Guid("6d63584c-813f-48de-9b19-df143f83d2f7"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 101,
                            Value = 1.61m
                        },
                        new
                        {
                            Id = new Guid("abe77fdd-828e-4d79-9827-6953aeaad7e2"),
                            DistrictId = new Guid("d484cf5d-d07d-4e01-8aa4-c87747fa68fe"),
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            MinWeight = 0,
                            Value = 10m
                        },
                        new
                        {
                            Id = new Guid("01f0a024-2333-4d5f-9df6-523c6e891ef7"),
                            DistrictId = new Guid("d484cf5d-d07d-4e01-8aa4-c87747fa68fe"),
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            MinWeight = 101,
                            Value = 1.40m
                        },
                        new
                        {
                            Id = new Guid("2b02f1a3-61d9-450d-8539-a5ab050d83b7"),
                            DistrictId = new Guid("d484cf5d-d07d-4e01-8aa4-c87747fa68fe"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 101,
                            Value = 1.92m
                        },
                        new
                        {
                            Id = new Guid("69e15296-cd12-4aca-974c-c14cd610bedf"),
                            DistrictId = new Guid("05bb9082-20a8-4114-946b-cce72cedab19"),
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            MinWeight = 0,
                            Value = 10m
                        },
                        new
                        {
                            Id = new Guid("5e0d612e-97ad-4c28-bd62-e8659e2e92d8"),
                            DistrictId = new Guid("05bb9082-20a8-4114-946b-cce72cedab19"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 23,
                            Value = 2.84m
                        },
                        new
                        {
                            Id = new Guid("e3024a86-3ca5-414d-b33e-df573752d8b8"),
                            DistrictId = new Guid("05bb9082-20a8-4114-946b-cce72cedab19"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 71,
                            Value = 2.70m
                        },
                        new
                        {
                            Id = new Guid("d0944a1f-6da7-4711-846e-5978e107736d"),
                            DistrictId = new Guid("05bb9082-20a8-4114-946b-cce72cedab19"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 101,
                            Value = 2.06m
                        },
                        new
                        {
                            Id = new Guid("9500ad5a-380e-4a05-ab33-a92817125325"),
                            DistrictId = new Guid("05bb9082-20a8-4114-946b-cce72cedab19"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 301,
                            Value = 1.98m
                        },
                        new
                        {
                            Id = new Guid("d6b32c93-4ae1-402f-90d2-504f8820140f"),
                            DistrictId = new Guid("05bb9082-20a8-4114-946b-cce72cedab19"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 1501,
                            Value = 1.95m
                        },
                        new
                        {
                            Id = new Guid("5f2306a2-4ed5-4181-9e15-e60cb557e19b"),
                            DistrictId = new Guid("0c02aa0a-b0d4-477a-b4e9-0a5073d323bf"),
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            MinWeight = 0,
                            Value = 10m
                        },
                        new
                        {
                            Id = new Guid("ffb1cd61-db1e-4249-ab43-13bc5cae0353"),
                            DistrictId = new Guid("0c02aa0a-b0d4-477a-b4e9-0a5073d323bf"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 23,
                            Value = 2.70m
                        },
                        new
                        {
                            Id = new Guid("aa8816f7-ff17-498d-8930-1ade9993327f"),
                            DistrictId = new Guid("0c02aa0a-b0d4-477a-b4e9-0a5073d323bf"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 71,
                            Value = 2.55m
                        },
                        new
                        {
                            Id = new Guid("ee7894da-a1c8-4e8f-936b-28fb56281815"),
                            DistrictId = new Guid("0c02aa0a-b0d4-477a-b4e9-0a5073d323bf"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 101,
                            Value = 1.90m
                        },
                        new
                        {
                            Id = new Guid("0badeed9-a777-45a2-a6c8-0e86cdb2e930"),
                            DistrictId = new Guid("0c02aa0a-b0d4-477a-b4e9-0a5073d323bf"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 301,
                            Value = 1.83m
                        },
                        new
                        {
                            Id = new Guid("9f47b332-689d-435d-9c27-116c1d6aa41f"),
                            DistrictId = new Guid("0c02aa0a-b0d4-477a-b4e9-0a5073d323bf"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 1501,
                            Value = 1.80m
                        },
                        new
                        {
                            Id = new Guid("62c04c59-418c-46bd-bd17-05afc26cf04d"),
                            DistrictId = new Guid("34e425db-ff6c-4ab7-ac14-a1bd7a7c94a8"),
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            MinWeight = 0,
                            Value = 10m
                        },
                        new
                        {
                            Id = new Guid("ec5e05d9-e2de-4cd9-897f-c6eb441c3dc7"),
                            DistrictId = new Guid("34e425db-ff6c-4ab7-ac14-a1bd7a7c94a8"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 23,
                            Value = 2.55m
                        },
                        new
                        {
                            Id = new Guid("0ec48687-d2e4-4f58-9b74-2097d9991bdd"),
                            DistrictId = new Guid("34e425db-ff6c-4ab7-ac14-a1bd7a7c94a8"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 71,
                            Value = 2.41m
                        },
                        new
                        {
                            Id = new Guid("18f67810-8e0e-47c1-988d-c2737ce8ebee"),
                            DistrictId = new Guid("34e425db-ff6c-4ab7-ac14-a1bd7a7c94a8"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 101,
                            Value = 1.76m
                        },
                        new
                        {
                            Id = new Guid("9261fc39-e173-4268-9b90-d1534cd7e091"),
                            DistrictId = new Guid("34e425db-ff6c-4ab7-ac14-a1bd7a7c94a8"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 301,
                            Value = 1.69m
                        },
                        new
                        {
                            Id = new Guid("5e746c67-d994-4fb1-9e3b-ec364150110b"),
                            DistrictId = new Guid("34e425db-ff6c-4ab7-ac14-a1bd7a7c94a8"),
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            MinWeight = 1501,
                            Value = 1.66m
                        });
                });

            modelBuilder.Entity("ShipbuData.TransportMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NameTr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TransportMethods");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            Enabled = true,
                            NameEn = "Air",
                            NameTr = "Uçak"
                        },
                        new
                        {
                            Id = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            Enabled = true,
                            NameEn = "Sea Slow",
                            NameTr = "Yavaş Gemi"
                        },
                        new
                        {
                            Id = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            Enabled = true,
                            NameEn = "Sea Fast",
                            NameTr = "Hızlı Gemi"
                        },
                        new
                        {
                            Id = new Guid("730cd01e-fb25-4347-8932-2b4056252e73"),
                            Enabled = true,
                            NameEn = "Fast Vessel",
                            NameTr = "Speed Boat"
                        },
                        new
                        {
                            Id = new Guid("af3e3b1a-06d9-413f-99ad-3378458be832"),
                            Enabled = true,
                            NameEn = "Truck",
                            NameTr = "TIR"
                        },
                        new
                        {
                            Id = new Guid("a5fe9692-ef46-4376-919f-43aeaa0c07a0"),
                            Enabled = true,
                            NameEn = "Railway",
                            NameTr = "Tren"
                        });
                });

            modelBuilder.Entity("ShipbuData.TransportOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TransportOrders");
                });

            modelBuilder.Entity("ShipbuData.TransportOrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("varchar(34)");

                    b.Property<Guid>("TransportOrderId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TransportOrderId");

                    b.ToTable("TransportOrderItems");

                    b.HasDiscriminator<string>("Discriminator").HasValue("TransportOrderItem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ShipbuData.TransportOrderItemContainerType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NameTr")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("NameTr")
                        .IsUnique();

                    b.ToTable("TransportOrderItemContainerTypes");
                });

            modelBuilder.Entity("ShipbuData.TransportOrderItemFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AttachmentDescriptionEn")
                        .HasColumnType("longtext");

                    b.Property<string>("AttachmentDescriptionTr")
                        .HasColumnType("longtext");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DescriptionTr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NameTr")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NameEn")
                        .IsUnique();

                    b.HasIndex("NameTr")
                        .IsUnique();

                    b.ToTable("TransportOrderItemFeatures");
                });

            modelBuilder.Entity("ShipbuData.TransportOrderItemFeatureValue", b =>
                {
                    b.Property<Guid>("TransportOrderItemFeatureId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TransportOrderItemId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Attachment")
                        .HasColumnType("longtext");

                    b.HasKey("TransportOrderItemFeatureId", "TransportOrderItemId");

                    b.HasIndex("TransportOrderItemId");

                    b.ToTable("TransportOrderItemFeatureValue");
                });

            modelBuilder.Entity("ShipbuData.TransportRegion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDestination")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsOrigin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NameTr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TransportRegions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c194434c-7a4d-4d70-98df-1ecc78a333aa"),
                            Enabled = true,
                            IsDestination = true,
                            IsOrigin = false,
                            NameEn = "USA",
                            NameTr = "ABD"
                        },
                        new
                        {
                            Id = new Guid("aaaa0d64-abd7-4e96-aa49-35d4253e014f"),
                            Enabled = true,
                            IsDestination = true,
                            IsOrigin = false,
                            NameEn = "Canada",
                            NameTr = "Kanada"
                        },
                        new
                        {
                            Id = new Guid("5d751653-be94-44f4-afbe-5baf410ae321"),
                            Enabled = true,
                            IsDestination = true,
                            IsOrigin = false,
                            NameEn = "UK",
                            NameTr = "İngiltere"
                        },
                        new
                        {
                            Id = new Guid("39887e51-8a46-42c1-b621-699d96326883"),
                            Enabled = true,
                            IsDestination = true,
                            IsOrigin = false,
                            NameEn = "Europe",
                            NameTr = "Avrupa"
                        },
                        new
                        {
                            Id = new Guid("a524039f-30f6-4adf-8cd3-2e0859fd08ab"),
                            Enabled = true,
                            IsDestination = false,
                            IsOrigin = true,
                            NameEn = "China",
                            NameTr = "Çin"
                        });
                });

            modelBuilder.Entity("ShipbuData.TransportRegionMethod", b =>
                {
                    b.Property<Guid>("MethodId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("ETAMax")
                        .HasColumnType("int");

                    b.Property<int?>("ETAMin")
                        .HasColumnType("int");

                    b.Property<int>("Volume")
                        .HasColumnType("int");

                    b.HasKey("MethodId", "RegionId");

                    b.HasIndex("RegionId");

                    b.ToTable("TransportRegionMethod");

                    b.HasData(
                        new
                        {
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            RegionId = new Guid("c194434c-7a4d-4d70-98df-1ecc78a333aa"),
                            ETAMax = 5,
                            ETAMin = 3,
                            Volume = 6000
                        },
                        new
                        {
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            RegionId = new Guid("c194434c-7a4d-4d70-98df-1ecc78a333aa"),
                            ETAMax = 5,
                            ETAMin = 3,
                            Volume = 6000
                        },
                        new
                        {
                            MethodId = new Guid("730cd01e-fb25-4347-8932-2b4056252e73"),
                            RegionId = new Guid("c194434c-7a4d-4d70-98df-1ecc78a333aa"),
                            ETAMax = 5,
                            ETAMin = 3,
                            Volume = 6000
                        },
                        new
                        {
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            RegionId = new Guid("aaaa0d64-abd7-4e96-aa49-35d4253e014f"),
                            ETAMax = 5,
                            ETAMin = 3,
                            Volume = 6000
                        },
                        new
                        {
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            RegionId = new Guid("aaaa0d64-abd7-4e96-aa49-35d4253e014f"),
                            ETAMax = 5,
                            ETAMin = 3,
                            Volume = 6000
                        },
                        new
                        {
                            MethodId = new Guid("cbf432c2-fd9e-4618-9b8f-60be075beef1"),
                            RegionId = new Guid("aaaa0d64-abd7-4e96-aa49-35d4253e014f"),
                            ETAMax = 5,
                            ETAMin = 3,
                            Volume = 6000
                        },
                        new
                        {
                            MethodId = new Guid("730cd01e-fb25-4347-8932-2b4056252e73"),
                            RegionId = new Guid("aaaa0d64-abd7-4e96-aa49-35d4253e014f"),
                            ETAMax = 5,
                            ETAMin = 3,
                            Volume = 6000
                        },
                        new
                        {
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            RegionId = new Guid("5d751653-be94-44f4-afbe-5baf410ae321"),
                            ETAMax = 5,
                            ETAMin = 3,
                            Volume = 6000
                        },
                        new
                        {
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            RegionId = new Guid("5d751653-be94-44f4-afbe-5baf410ae321"),
                            ETAMax = 5,
                            ETAMin = 3,
                            Volume = 6000
                        },
                        new
                        {
                            MethodId = new Guid("af3e3b1a-06d9-413f-99ad-3378458be832"),
                            RegionId = new Guid("5d751653-be94-44f4-afbe-5baf410ae321"),
                            ETAMax = 5,
                            ETAMin = 3,
                            Volume = 6000
                        },
                        new
                        {
                            MethodId = new Guid("7875cc3c-a338-480a-98d8-8d3296575000"),
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883"),
                            ETAMax = 5,
                            ETAMin = 3,
                            Volume = 6000
                        },
                        new
                        {
                            MethodId = new Guid("96e1ef5b-916c-4885-ae5b-08a98541e92a"),
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883"),
                            ETAMax = 5,
                            ETAMin = 3,
                            Volume = 6000
                        },
                        new
                        {
                            MethodId = new Guid("a5fe9692-ef46-4376-919f-43aeaa0c07a0"),
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883"),
                            ETAMax = 5,
                            ETAMin = 3,
                            Volume = 6000
                        },
                        new
                        {
                            MethodId = new Guid("af3e3b1a-06d9-413f-99ad-3378458be832"),
                            RegionId = new Guid("39887e51-8a46-42c1-b621-699d96326883"),
                            ETAMax = 5,
                            ETAMin = 3,
                            Volume = 6000
                        });
                });

            modelBuilder.Entity("ShipbuData.TransportStaticPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ContentEn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ContentTr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LabelEn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LabelTr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Views")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TransportStaticPages");
                });

            modelBuilder.Entity("ShipbuData.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("RefreshToken")
                        .HasColumnType("char(36)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("TransportOrderItemTransportOrderItemFeature", b =>
                {
                    b.Property<Guid>("TransportOrderItemFeaturesId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TransportOrderItemsId")
                        .HasColumnType("char(36)");

                    b.HasKey("TransportOrderItemFeaturesId", "TransportOrderItemsId");

                    b.HasIndex("TransportOrderItemsId");

                    b.ToTable("TransportOrderItemTransportOrderItemFeature");
                });

            modelBuilder.Entity("ShipbuData.TransportOrderItemContainer", b =>
                {
                    b.HasBaseType("ShipbuData.TransportOrderItem");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("TransportOrderItemContainerTypeId")
                        .HasColumnType("char(36)");

                    b.Property<float>("Weight")
                        .HasColumnType("float");

                    b.HasIndex("TransportOrderItemContainerTypeId");

                    b.HasDiscriminator().HasValue("TransportOrderItemContainer");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("ShipbuData.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("ShipbuData.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("ShipbuData.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("ShipbuData.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShipbuData.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("ShipbuData.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShipbuData.TransportDistrict", b =>
                {
                    b.HasOne("ShipbuData.TransportRegion", "Region")
                        .WithMany("Districts")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("ShipbuData.TransportFee", b =>
                {
                    b.HasOne("ShipbuData.TransportDistrict", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShipbuData.TransportMethod", "Method")
                        .WithMany()
                        .HasForeignKey("MethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");

                    b.Navigation("Method");
                });

            modelBuilder.Entity("ShipbuData.TransportOrder", b =>
                {
                    b.HasOne("ShipbuData.User", "User")
                        .WithMany("TransportOrders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShipbuData.TransportOrderItem", b =>
                {
                    b.HasOne("ShipbuData.TransportOrder", "TransportOrder")
                        .WithMany("TransportOrderItems")
                        .HasForeignKey("TransportOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransportOrder");
                });

            modelBuilder.Entity("ShipbuData.TransportOrderItemFeatureValue", b =>
                {
                    b.HasOne("ShipbuData.TransportOrderItemFeature", "TransportOrderItemFeature")
                        .WithMany("TransportOrderItemFeatureValues")
                        .HasForeignKey("TransportOrderItemFeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShipbuData.TransportOrderItem", "TransportOrderItem")
                        .WithMany("TransportOrderItemFeatureValues")
                        .HasForeignKey("TransportOrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransportOrderItem");

                    b.Navigation("TransportOrderItemFeature");
                });

            modelBuilder.Entity("ShipbuData.TransportRegionMethod", b =>
                {
                    b.HasOne("ShipbuData.TransportMethod", "Method")
                        .WithMany("TransportRegionMethods")
                        .HasForeignKey("MethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShipbuData.TransportRegion", "Region")
                        .WithMany("TransportRegionMethods")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Method");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("TransportOrderItemTransportOrderItemFeature", b =>
                {
                    b.HasOne("ShipbuData.TransportOrderItemFeature", null)
                        .WithMany()
                        .HasForeignKey("TransportOrderItemFeaturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShipbuData.TransportOrderItem", null)
                        .WithMany()
                        .HasForeignKey("TransportOrderItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TransportOrderItemTransportOrderItemFeature_TransportOrderI~1");
                });

            modelBuilder.Entity("ShipbuData.TransportOrderItemContainer", b =>
                {
                    b.HasOne("ShipbuData.TransportOrderItemContainerType", "TransportOrderItemContainerType")
                        .WithMany("TransportOrderItemContainers")
                        .HasForeignKey("TransportOrderItemContainerTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TransportOrderItemContainerType");
                });

            modelBuilder.Entity("ShipbuData.TransportMethod", b =>
                {
                    b.Navigation("TransportRegionMethods");
                });

            modelBuilder.Entity("ShipbuData.TransportOrder", b =>
                {
                    b.Navigation("TransportOrderItems");
                });

            modelBuilder.Entity("ShipbuData.TransportOrderItem", b =>
                {
                    b.Navigation("TransportOrderItemFeatureValues");
                });

            modelBuilder.Entity("ShipbuData.TransportOrderItemContainerType", b =>
                {
                    b.Navigation("TransportOrderItemContainers");
                });

            modelBuilder.Entity("ShipbuData.TransportOrderItemFeature", b =>
                {
                    b.Navigation("TransportOrderItemFeatureValues");
                });

            modelBuilder.Entity("ShipbuData.TransportRegion", b =>
                {
                    b.Navigation("Districts");

                    b.Navigation("TransportRegionMethods");
                });

            modelBuilder.Entity("ShipbuData.User", b =>
                {
                    b.Navigation("TransportOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
